// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -825115637,
    "VotePlayer"
  ],
  /* tuple */[
    -75165210,
    "VoteAnimal"
  ],
  /* tuple */[
    3455931,
    "End"
  ],
  /* tuple */[
    575593267,
    "TurnAction"
  ],
  /* tuple */[
    815032112,
    "Init"
  ]
];

function gameStepToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray);
}

function gameStepFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray, param);
}

console.log(gameStepFromJs("Init"));

console.log(gameStepToJs(/* Init */815032112));

function init(playerCount) {
  return {
          state: /* Init */815032112,
          playerCount: playerCount
        };
}

function gameReducer(state, action) {
  var match = gameStepFromJs(action.type);
  if (match !== undefined) {
    if (match !== 815032112) {
      return Js_primitive.some(state);
    } else {
      return {
              state: /* Init */815032112,
              playerCount: 8
            };
    }
  }

}

var s = "安安";

exports.s = s;
exports.gameStepToJs = gameStepToJs;
exports.gameStepFromJs = gameStepFromJs;
exports.init = init;
exports.gameReducer = gameReducer;
/*  Not a pure module */
