// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -825115637,
    "VotePlayer"
  ],
  /* tuple */[
    -75165210,
    "VoteAnimal"
  ],
  /* tuple */[
    3455931,
    "End"
  ],
  /* tuple */[
    575593267,
    "TurnAction"
  ],
  /* tuple */[
    815032112,
    "Init"
  ]
];

function gameStepToJs(param) {
  return Js_mapperRt.binarySearch(5, param, jsMapperConstantArray);
}

function gameStepFromJs(param) {
  return Js_mapperRt.revSearch(5, jsMapperConstantArray, param);
}

console.log(gameStepFromJs("Init"));

console.log(gameStepToJs(/* Init */815032112));

function init(playerCount) {
  return {
          state: gameStepToJs(/* Init */815032112),
          playerCount: playerCount
        };
}

function endGame() {
  return {
          state: gameStepToJs(/* End */3455931),
          playerCount: 0
        };
}

function turnAction(_, _$1) {
  var partial_arg = gameStepToJs(/* TurnAction */575593267);
  return (function (param) {
      return {
              state: partial_arg,
              playerCount: param
            };
    });
}

function gameReducer(state, action) {
  var match = gameStepFromJs(action.type);
  if (match !== undefined) {
    var s = match;
    if (s !== 3455931) {
      if (s !== 575593267) {
        if (s !== 815032112) {
          return state;
        } else {
          return {
                  state: gameStepToJs(/* Init */815032112),
                  playerCount: 8
                };
        }
      } else {
        console.log("action");
        console.log(action);
        return {
                state: gameStepToJs(/* End */3455931),
                playerCount: 0
              };
      }
    } else {
      console.log("action");
      console.log(action);
      return {
              state: gameStepToJs(/* End */3455931),
              playerCount: 0
            };
    }
  } else {
    return state;
  }
}

var s = "安安";

exports.s = s;
exports.gameStepToJs = gameStepToJs;
exports.gameStepFromJs = gameStepFromJs;
exports.init = init;
exports.endGame = endGame;
exports.turnAction = turnAction;
exports.gameReducer = gameReducer;
/*  Not a pure module */
